# Welcome to Jekyll!
#

# Site settings
title: Zachary Taylor
description: |
  Student --- Developer
owner: Zachary Taylor # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: ztaylor54@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ztaylor54.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/ztaylor54
  github: https://github.com/ztaylor54
  linkedin-square: https://linkedin.com/in/ztaylor54
  facebook-official: https://facebook.com/zachary.taylor.1428
  google-plus-square: https://plus.google.com/u/0/+ztaylor54
  email: /contact/
  #flickr:
  instagram: ztaylor54
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
